// Unique flavor descriptions for each brand
// Each flavor has a unique description per brand to reflect brand-specific formulations

export const flavorDescriptions: Record<string, Record<string, string>> = {
  // Adjust by Lost Mary
  adjust: {
    'Tigers blood': 'Watermelon, strawberry, and coconut fusion with cherry hints, delivering a tropical shaved ice flavor with smooth throat hit.',
    'Sour pinkberry': 'Tangy pink berries meet a sour candy coating, delivering an intense sweet-tart experience unique to the Adjust line.',
    'Wintergreen savers': 'Classic wintergreen mint candy flavor with a cooling sensation and sweet undertones, perfectly balanced for all-day vaping.',
    'Watermelon mango peach': 'Juicy watermelon leads with tropical mango and soft peach notes following, creating a summer fruit medley.',
    'Sour island': 'Tropical island fruits featuring tangy pineapple, sour mango, and citrus lime with a tart candy finish.',
    'Blue raz ice': 'Bold blue raspberry candy flavor enhanced with a refreshing menthol finish for a cool, sweet vape.',
    'Watermelon roll ups': 'Nostalgic fruit roll-up candy flavor featuring concentrated watermelon sweetness with a chewy candy essence.',
    'Baja splash': 'Tropical citrus soda-inspired blend with lime, pineapple, and a fizzy sensation reminiscent of mountain drinks.',
    'Raspberry orange': 'Tart raspberries perfectly balanced with zesty orange citrus for a refreshing fruit combination.',
    'Lemon heads': 'Intense lemon candy flavor that starts sour and finishes sweet, just like the classic hard candy.',
    'Sour lush gummy': 'Watermelon gummy candy with an extra sour coating, delivering chewy sweetness with a tangy punch.',
    'Dragon strawberry banana': 'Exotic dragon fruit meets classic strawberry-banana smoothie for a creamy tropical experience.',
    'Raspberry watermelon': 'Sweet watermelon enhanced with tart raspberry notes for a perfectly balanced summer fruit blend.',
    'Triple berry grape': 'Three berry blend of strawberry, blueberry, and blackberry with sweet grape undertones.',
    'Pineapple ice peach': 'Tropical pineapple and soft peach with a cooling menthol exhale for refreshing sweetness.',
    'Watermelon b-pop': 'Frozen watermelon popsicle flavor with authentic fruit sweetness and an icy finish.',
    'Triple berry': 'A harmonious blend of strawberry, blueberry, and raspberry creating the ultimate berry experience.',
    'Cherry fuse': 'Bold cherry flavor with mixed fruit undertones creating an explosive taste sensation.',
    'Strawberry mint candy': 'Sweet strawberry hard candy with refreshing mint crystals for a unique flavor combination.',
    'Mixed mint': 'Multiple mint varieties including spearmint, peppermint, and wintergreen for complex cooling.',
    'Orange strawberry': 'Citrus orange brightness meets strawberry sweetness in perfect harmony.',
    'Tangerine white gummy': 'Tangy tangerine citrus with creamy white gummy bear sweetness.',
    'Peach': 'Pure, ripe peach flavor with natural sweetness and subtle floral notes.',
    'Midnight ice chill': 'Dark blackberry and blueberry blend with hints of grape and an intense menthol freeze for arctic-level cooling.',
    'Watermelon Ice': 'Crisp watermelon with arctic menthol creating a refreshing summer chill.',
    'Strawberry Banana': 'Creamy banana smoothie blended with ripe strawberries for a classic fruit combination.',
    'Summer Splash': 'A vibrant mix of summer fruits including melon, berries, and citrus for poolside vibes.',
    'Sour Apple Ice': 'Green apple tartness with a sour candy coating and cooling menthol finish.',
    'Blue Razz B Pop': 'Blue raspberry popsicle with authentic frozen treat sweetness.',
    'Sour Blue Razz Ice': 'Extra sour blue raspberry with an icy menthol blast for intense flavor.',
    'Sour Peach Raspberry': 'Tangy peach and tart raspberry with a sour candy coating.',
    'Sour Grapple': 'Sour green apple mixed with purple grape for a unique tart-sweet combination.',
  },

  // Geek Bar Ria
  ria: {
    'Sour Strawberry Dragon': 'Geek Bar\'s signature dragon fruit blend with sour strawberry notes, creating an exotic sweet-tart experience.',
    'Miami Mint': 'Cool spearmint and peppermint blend with hints of coconut and lime for a tropical mint experience.',
    'Blue Razz Ice': 'Sweet and tangy blue raspberry candy with menthol ice creating a frozen slush drink flavor.',
    'Fcuking Fab': 'Tropical fruit punch combining sweet mango, tangy pineapple, and mixed berries with a candy-like sweetness - Geek Bar\'s most iconic flavor.',
    'Pineapple Lime': 'Tangy pineapple chunks with zesty lime squeeze for a tropical citrus explosion.',
    'Dualicuous': 'Geek Bar\'s dual-flavor technology delivering alternating taste sensations with each puff.',
    'Pink Razz Lemonade': 'Raspberry lemonade with a pink candy twist, perfectly sweet and tart.',
    'Blueberry Punch': 'Bold blueberry flavor with mixed fruit punch for a berry-forward cocktail experience.',
    'Peach Gummy': 'Soft peach gummy candy flavor with authentic chewy sweetness.',
    'Crazy Berry': 'Wild berry mix that changes notes with each inhale for a crazy flavor journey.',
    'Watermelon Ice': 'Geek Bar\'s premium watermelon extract with their signature cooling technology.',
  },

  // Digiflavor Skyview
  skyview: {
    'Skywalker': 'Grape and mixed berry blend with hints of menthol, creating a sweet and cooling galactic fruit experience.',
    'Strawberry Ice': 'Premium strawberry essence with Skyview\'s advanced cooling system for pure refreshment.',
    'Triple Berry': 'Three-layer berry experience with distinct strawberry, blueberry, and blackberry notes.',
    'Miami Mint': 'Digiflavor\'s interpretation of the famous mint with added complexity and smoothness.',
    'Sour Apple Ice': 'Granny Smith apple sourness with candy coating and ice-cold finish.',
    'Peach Blue Slushy': 'Frozen peach and blue raspberry slush drink with authentic brain-freeze sensation.',
    'Strawberry Watermelon Coconut': 'Tropical paradise blend with creamy coconut smoothing the fruit combination.',
    'Cherry Lemon Mint': 'Unique cherry lemonade with fresh mint leaves for a sophisticated flavor profile.',
  },

  // Geek Bar Pulse X
  pulse_x: {
    'ATL Mint (Meteor / Patriot Edition)': 'Atlanta-inspired mint blend exclusive to the special edition, with cooling intensity.',
    'Banana Taffy Freeze': 'Creamy banana taffy candy with Pulse X\'s signature freeze technology.',
    'Blackberry Blueberry': 'Dark berry duo creating deep, rich fruit flavor with natural sweetness.',
    'Blackberry B‑Pop': 'Frozen blackberry popsicle with authentic ice pop sweetness.',
    'Blue Rancher': 'Blue raspberry hard candy inspired by ranch-style sweets.',
    'Blue Razz Ice': 'Pulse X\'s enhanced blue raspberry with dual-mesh cooling technology.',
    'Cool Mint': 'Pure, clean mint flavor optimized for the Pulse X\'s advanced airflow.',
    'Cola Slush (Slush Edition)': 'Frozen cola with crushed ice texture, part of the exclusive Slush series.',
    'Grape Slush (Slush Edition)': 'Purple grape slush drink with brain-freeze sensation.',
    'Orange Slush (Slush Edition)': 'Tangy orange slush with citrus zest and icy texture.',
    'Peach Perfect Slush (Slush Edition)': 'Georgia peach slush with perfect sweetness balance.',
    'Wild Cherry Slush (Slush Edition)': 'Bold cherry slush completing the Slush Edition lineup.',
    'Grapefruit Refresher': 'Pink grapefruit with subtle sweetness for a refreshing citrus experience.',
    'Lemon Heads': 'Classic lemon candy with Pulse X\'s enhanced flavor delivery.',
    'Lime Berry Orange': 'Citrus trilogy with berry accents for complex fruit layering.',
    'Miami Mint': 'Spearmint and peppermint with coconut undertones and lime zest for a tropical mint blend.',
    'Orange Dragon (Meteor Edition)': 'Orange citrus with dragon fruit, exclusive to Meteor Edition.',
    'Orange Fcuking Fab': 'Orange-enhanced version of Geek Bar\'s legendary Fcuking Fab.',
    'Pink & Blue (Meteor Edition)': 'Cotton candy inspired dual-flavor from the Meteor collection.',
    'Punch (Platinum Edition)': 'Premium fruit punch blend exclusive to Platinum Edition.',
    'Raspberry Peach Lime': 'Three-fruit harmony with tart and sweet balance.',
    'Sour Apple Ice': 'Extra sour green apple with Pulse X cooling technology.',
    'Sour Fcuking Fab': 'Sour candy version of the famous Fcuking Fab flavor.',
    'Sour Mango Pineapple': 'Tropical duo with added sourness for intensity.',
    'Sour Straws': 'Rainbow sour straw candy with authentic tangy coating.',
    'Strawberry B‑Pop': 'Strawberry popsicle with creamy undertones.',
    'Strawberry Colada': 'Piña colada with fresh strawberry twist.',
    'Strawberry Kiwi Ice (Meteor Edition)': 'Classic combo enhanced for Meteor Edition.',
    'Strawberry Watermelon (Meteor Edition)': 'Summer fruits perfected in Meteor Edition.',
    'Watermelon Ice': 'Pulse X\'s signature watermelon with maximum cooling.',
    'White Peach Raspberry': 'Delicate white peach with tart raspberry balance.',
    'Strawberry Jam (Jam Edition)': 'Thick strawberry preserve flavor from Jam Edition.',
    'Blueberry Jam (Jam Edition)': 'Sweet blueberry jam with authentic fruit chunks.',
    'Raspberry Jam (Jam Edition)': 'Tart raspberry preserve from the Jam collection.',
    'Peach Jam (Jam Edition)': 'Southern peach jam with homemade sweetness.',
    'Orange Jam (Jam Edition)': 'Marmalade-style orange jam completing the collection.',
  },

  // Geek Bar Pulse
  pulse: {
    'Sour Cranapple': 'Cranberry and apple with sour candy coating, exclusive to original Pulse.',
    'Creamy Mintz': 'Vanilla cream blended with mint for dessert-like satisfaction.',
    'Black Mintz': 'Dark mint variety with complex herbal notes.',
    'Stone Mintz': 'Mineral-enhanced mint for unique cooling sensation.',
    'Icy Mintz': 'Maximum ice mint blend for extreme cooling.',
    'Watermelon Ice': 'Original Pulse watermelon formula with balanced cooling.',
    'Fcuking FAB': 'The original tropical fruit punch with mango, pineapple, and berry notes that started the legend.',
    'Wild Berry Savers': 'Mixed berry hard candy with life-saver style sweetness.',
    'Strawberry Savers': 'Strawberry candy ring flavor with creamy center notes.',
    'Pineapple Savers': 'Tropical pineapple candy with signature sweetness.',
    'Orange Mint Savers': 'Orange candy with mint crystal center.',
    'Spooky Vanilla': 'Creamy vanilla custard with hints of cinnamon spice and caramel undertones for a hauntingly sweet vape.',
    'Sour Gush': 'Fruit gusher candy with extra sour liquid center.',
    'Sour Blue Dust': 'Blue raspberry with sour powder coating.',
    'Sour Strawberry': 'Strawberry candy with intense sour finish.',
    'Sour Watermelon Drop': 'Watermelon hard candy with sour center.',
    'Frozen Strawberry': 'Flash-frozen strawberry with icy texture.',
    'Frozen Pina Colada': 'Frozen tropical cocktail with coconut cream.',
    'Frozen Cherry Apple': 'Cherry and apple with arctic freeze.',
    'Frozen Blackberry Fab': 'Blackberry version of Fcuking Fab, frozen edition.',
    'Frozen Watermelon': 'Sub-zero watermelon for maximum chill.',
    'Frozen White Grape': 'White grape with crystalline ice finish.',
    'Sour Apple B‑Pop': 'Green apple popsicle with sour coating.',
    'Grape Lemon': 'Purple grape with lemon zest for unique combination.',
    'Orange Creamsicle': 'Classic orange cream bar perfectly recreated.',
    'Dragon Melon': 'Dragon fruit and melon fusion.',
    'OMG B‑Pop': 'Blue raspberry and cherry popsicle with a hint of grape, creating a sweet frozen treat flavor.',
    'Grape B‑Pop': 'Grape popsicle with authentic frozen treat taste.',
    'Crazy Melon': 'Multiple melon varieties for crazy fruit experience.',
    'Black Cherry': 'Dark, rich cherry with subtle sweetness.',
    'Blueberry Watermelon': 'Unexpected pairing creating perfect harmony.',
    'Berry Bliss': 'Berry medley designed for pure satisfaction.',
    'Cherry Bomb': 'Explosive cherry flavor with candy intensity.',
    'Cool Mint': 'Clean, refreshing mint optimized for Pulse system.',
    'Blue Razz Ice': 'Original Pulse blue raspberry ice formula.',
    'Miami Mint': 'Cool mint blend with spearmint, peppermint, and hints of tropical coconut.',
    'Pink Lemonade': 'Sweet pink lemonade with candy notes.',
    'Mexico Mango': 'Authentic Mexican mango with chili hint.',
    'Juicy Peach Ice': 'Ripe peach with subtle cooling.',
    'Meta Moon': 'Papaya, watermelon, and strawberry blend creating a sweet, exotic fruit combination with subtle cooling.',
    'California Cherry': 'West coast cherry with unique profile.',
    'Blue Mint': 'Blue-tinted mint with enhanced cooling.',
  },

  // Geek Bar Meloso
  meloso: {
    'Stone Freeze': 'Meloso\'s signature stone fruit blend with maximum freeze technology for an intense cooling experience.',
  },

  // Razz LTX
  ltx: {
    'Orange Pineapple Punch': 'Razz\'s tropical punch recipe with dominant orange and pineapple notes.',
    'Orange Berry Lime Ice': 'Citrus-forward blend with mixed berries and lime, finished with LTX cooling.',
    'Frozen Cherry Apple': 'Razz\'s take on cherry apple with their signature frozen treatment.',
    'Clear': 'No flavor - just pure, clean vapor with slight sweetness from the VG/PG base.',
    'Tobacco': 'Rich, earthy tobacco with hints of caramel and nutty undertones for a smooth cigarette-like taste.',
    'Cherry Strapple': 'Cherry, strawberry, and apple trinity unique to Razz.',
    'Strawberry Orange Tang': 'Tangy orange drink with strawberry sweetness.',
    'Black & Blue Lime': 'Blackberry and blueberry with lime accent.',
    'Clear Sapphire': 'Enhanced clear flavor with cooling sensation.',
    'Fire & Ice': 'Cinnamon heat with menthol cooling for contrast.',
    'Pink Lemonade Minty O\'s': 'Pink lemonade with mint candy circles.',
    'Watermelon Ice': 'Razz LTX\'s premium watermelon ice blend.',
    'Iced Blue Dragon': 'Blue dragon fruit with intense ice.',
    'Sour Watermelon Peach': 'Watermelon and peach with sour enhancement.',
    'Frozen Banana': 'Creamy banana with frozen texture.',
    'Rainbow Rain': 'Skittles-inspired rainbow fruit shower.',
    'Miami Mint': 'Razz\'s interpretation of the famous mint.',
    'Raspberry Limeade': 'Tart raspberry with lime soda inspiration.',
    'Strawberry Kiwi Pear': 'Three-fruit blend with unique pear addition.',
    'Sour Apple Watermelon': 'Green apple and watermelon with sour coating.',
    'Sour Apple Ice': 'Maximum sourness with cooling finish.',
    'Frozen Raspberry Watermelon': 'Summer fruits with arctic treatment.',
    'Frozen Dragonfruit Lemon': 'Exotic dragon fruit with lemon freeze.',
    'Bangin Sour Berries': 'Intense sour berry explosion.',
    'Blue Razz Ice': 'Blue raspberry candy with crushed ice and menthol for a sweet frozen slush flavor.',
    'Orange Mango': 'Tropical orange and mango blend.',
  },

  // Razz Mega
  razz_mega: {
    'Dragon Fruit Lemonade': 'Exotic dragon fruit mixed with house-made lemonade for Razz Mega\'s signature drink flavor.',
    'Tiffany': 'Blue raspberry and kiwi blend with a cool mint finish, creating Razz\'s signature Tiffany blue experience.',
    'Black Cherry Peach': 'Dark cherry sweetness balanced with soft peach for a unique Razz blend.',
    'Strawberry Orange Mango': 'Triple fruit tropical blend optimized for the Mega\'s airflow.',
    'Day Crawler': 'Bright, energizing citrus blend designed for daytime vaping.',
    'Night Crawler': 'Dark mixed berries including blackberry, blueberry, and black currant with a sweet candy coating.',
    'Blueberry Watermelon': 'Classic Razz combination with perfect fruit balance.',
    'Cactus Jack': 'Prickly pear cactus with citrus notes, Razz\'s desert-inspired creation.',
    'Mango Colada': 'Tropical mango piña colada with coconut cream.',
    'Peach Grapefruit': 'Southern peach meets tart grapefruit for sophisticated flavor.',
    'Strawberry Watermelon': 'Razz Mega\'s take on the classic summer combination.',
    'Watermelon Ice': 'Crisp watermelon with Mega\'s cooling system.',
    'Graham Twist': 'Graham cracker dessert flavor with cinnamon notes.',
    'Miami Mint': 'Razz\'s version of the legendary Miami Mint.',
    'Black Cherry Kiwi': 'Dark cherry with tangy kiwi for unique pairing.',
    'Georgia Peach': 'Authentic Southern peach with natural sweetness.',
    'Blue Razz B Pop': 'Blue raspberry popsicle, Razz style.',
    'White Gummy Watermelon': 'White gummy bear with watermelon twist.',
    'White Yummy Grape': 'White grape gummy candy flavor.',
  },

  // Lost Mary MO20000
  lm20000: {
    'Tropical Punch': 'Lost Mary\'s tropical fruit punch with multiple exotic fruits.',
    'Orange Pomegranate Cranberry': 'Sophisticated citrus blend with tart pomegranate and cranberry.',
    'Strawberry Kiwi': 'Classic pairing perfected by Lost Mary\'s flavor team.',
    'Arizona Ice Tea': 'Authentic Arizona-style iced tea with subtle sweetness.',
    'Pure Ice': 'Maximum menthol with no added flavors.',
    'Dragon Drink': 'Dragon fruit beverage inspired by popular coffee shop drinks.',
    'Blue Razz Ice': 'Sweet blue raspberry candy with menthol crystals creating an icy berry slush.',
    'Miami Mint': 'Refreshing spearmint with peppermint and subtle coconut for a beach-inspired mint.',
    'Grape Jelly': 'Thick, sweet grape jelly spread flavor.',
    'Sour Strawberry Dragon': 'Dragon fruit and strawberry with sour enhancement.',
    'Sour Apple Ice': 'Tart green apple with cooling finish.',
    'Watermelon Sour Peach': 'Watermelon sweetness with sour peach contrast.',
    'Strawberry Ice': 'Pure strawberry with menthol cooling.',
    'Peach +': 'Juicy peach enhanced with apricot and nectarine notes, plus a touch of honey sweetness.',
    'Rocket Popsicle': 'Red, white, and blue popsicle recreation.',
    'Pure': 'Flavorless option providing clean vapor with natural sweetness from the base liquid.',
    'Lime Grapefruit': 'Citrus duo with perfect tart balance.',
    'Pear Drop': 'British pear drop candy perfectly recreated.',
    'Luxury Tobacco': 'Smooth Virginia tobacco with notes of honey, vanilla, and toasted oak for a refined taste.',
    'Red Wave': 'Strawberry, watermelon, and red apple creating a wave of sweet red fruit flavors.',
    'Pina Colada': 'Tropical cocktail with coconut and pineapple.',
    'Blue Baja Splash': 'Mountain-inspired blue citrus blast.',
    'Mountain Berry': 'Mixed mountain berries with alpine freshness.',
    'Deep Purple': 'Dark grape and berry blend with depth.',
    'Hawaiian Popsicle': 'Tropical fruit popsicle with island flavors.',
    'Peppermint': 'Pure peppermint with candy sweetness.',
    'Rainbow Sherbert': 'Multi-flavor sherbet ice cream.',
    'Pineapple Ice': 'Tropical pineapple with cooling effect.',
    'Scarry Berry': 'Mixed berry medley with strawberry, blueberry, and blackberry, plus a tangy sour twist.',
  },

  // Lost Mary MT15000 Turbo
  lmmt15000: {
    'Grape Jelly': 'Turbo-enhanced grape jelly with concentrated flavor.',
    'Tropical Baja Splash': 'Tropical version of the Baja splash for MT15000.',
    'Wild Berry Baja Splash': 'Berry-infused Baja splash variant.',
    'Acai Storm Ice': 'Superfruit acai with storm-level cooling.',
    'Hawaii Juice': 'Mixed Hawaiian fruit juice blend.',
    'Refresh Fcucking Fab': 'Tropical fruit punch with mango, pineapple, mixed berries, and extra cooling menthol.',
    'Peach Blue Slushy': 'Peach and blue raspberry frozen drink.',
    'Sour Strawberry Peach': 'Double fruit with sour intensity.',
    'Green Apple Lime': 'Tart apple with lime zest.',
    'Berry Burst': 'Explosive mixed berry flavor.',
    'Pacific Cooler': 'Tropical Pacific fruit blend.',
    'Blueberry Raspberry Lemon': 'Triple fruit with citrus finish.',
    'Grape Apple': 'Unique grape and apple combination.',
    'Rainbow Bubblegum': 'Multi-flavor bubblegum experience.',
    'Grapefruit Berries': 'Citrus grapefruit with mixed berries.',
    'Red Strawberry': 'Pure, intense strawberry flavor.',
    'Purple Passion Punch': 'Passion fruit punch with purple fruits.',
    'Raspberry Watermelon': 'Tart raspberry meets sweet watermelon.',
    'Citrus Sunrise': 'Morning citrus blend with energy.',
    'Summer Grape': 'Light, refreshing grape for summer.',
    'Yellow Lemon': 'Bright yellow lemon with sweetness.',
  },

  // Lost Mary MO5000
  mo5000: {
    'Pineapple Apple Pear': 'Triple fruit blend with tropical and orchard fruits.',
    'Kiwi Fuse': 'Intense kiwi flavor with electric sensation.',
    'Kiwi Dragon Duo Ice': 'Kiwi and dragon fruit duo with ice.',
    'Strawberry Watermelon Ice': 'Classic combo with MO5000 cooling.',
    'Black Cherry Melon': 'Dark cherry with honeydew melon.',
    'Mango Peach': 'Tropical mango meets Georgia peach.',
    'Kiwi Honey Dew Apple': 'Unique triple fruit with honey notes.',
    'Hawaii Juice': 'MO5000\'s Hawaiian fruit juice blend.',
    'Mango Peach Watermelon': 'Triple fruit summer blend.',
    'Blue Trio': 'Three blue-tinted fruits combined.',
    'White Strawberry Ice': 'White strawberry variant with cooling.',
    'Blueberry Raspberry Lemon': 'Berry duo with lemon brightness.',
    'Triple Berry Ice': 'Three berries with cooling finish.',
    'Strawberry Kiwi Ice': 'Classic pairing with ice enhancement.',
    'Kiwi Dragonfruit Berry Ice': 'Complex fruit blend with cooling.',
    'Watermelon Cherry': 'Summer watermelon with cherry accent.',
    'Berry Rose Duo Ice': 'Berries with rose notes and ice.',
    'Pure': 'Unflavored pure vapor option.',
    'Fuji Duo Ice': 'Fuji apple blend with cooling.',
    'Gami': 'Mixed fruit gummy bears featuring pineapple, orange, strawberry, and green apple candy flavors.',
    'Guava Ice': 'Tropical guava with menthol.',
    'Grape Cloudo': 'Grape with cloud-like texture.',
    'Black Duo Ice': 'Dark fruit duo with ice.',
    'Banana Raspberry Ice': 'Creamy banana with tart raspberry.',
    'Cherry Lemon': 'Cherry lemonade inspiration.',
    'Cherry Blossom Grape': 'Floral cherry with grape.',
    'Berry Cake': 'Berry dessert flavor.',
    'Watermelon Ice': 'Pure watermelon with cooling.',
  },

  // Los Gal by Lost Mary
  losgal: {
    'Watermelon Ice': 'Los Gal\'s crisp watermelon with signature ice blend for all-day refreshment.',
    'Strawberry Orange Pineapple': 'Tropical fruit salad with perfect sweet-tart balance.',
    'Triple Berry': 'Los Gal\'s premium three-berry blend with natural sweetness.',
    'Orange Mango Guava': 'Exotic tropical trio creating paradise in every puff.',
    'Sour Apple Grape Kiwi': 'Unique sour fruit combination exclusive to Los Gal.',
  },

  // Viho Supercharge Pro
  viho_sp: {
    'White Peach Razz': 'Delicate white peach with raspberry tartness, Viho\'s premium blend.',
    'Strawberry Colada': 'Strawberry-infused piña colada with coconut cream.',
    'Smooth Tobacco': 'Mild tobacco with creamy vanilla and caramel notes, creating a mellow cigarette alternative.',
    'Peach Rings': 'Gummy peach ring candy perfectly recreated.',
    'Strawberry Ice': 'Fresh strawberry with Supercharge cooling.',
    'Sour Apple Ice': 'Green apple sourness with ice finish.',
    'Tobacco Mint': 'Smooth tobacco with cool spearmint creating a menthol cigarette-like experience.',
    'Orange Splash': 'Citrus orange with splash of tropical fruits.',
    'Sour Apple Fcucking Fab': 'Viho\'s sour apple take on the legendary flavor.',
  },

  // Viho Supercharge
  viho_s: {
    'Blueberry Pom': 'Blueberry pomegranate antioxidant blend.',
    'Rainbow Candy': 'Multi-flavor rainbow candy experience.',
    'Icy Mint': 'Viho\'s iciest mint formulation.',
    'Sour Apple Ice': 'Tart apple with Supercharge cooling.',
    'Lemon Pie': 'Creamy lemon pie dessert flavor.',
    'Raspberry Orange': 'Tart raspberry with citrus orange.',
    'Blueberry Ice': 'Sweet blueberry with cooling finish.',
    '6ixty Nine': 'Tropical passion fruit and orange blend with hints of guava and mango for a sweet citrus experience.',
    'Mango Magic': 'Magical mango with tropical notes.',
    'Pineapple Apple Pear': 'Triple fruit harmony.',
    'Clear': 'No added flavor - clean vapor with subtle natural sweetness from the base.',
    'Strawberry Mango': 'Sweet strawberry meets tropical mango.',
    'Georgia Peach': 'Authentic Southern peach flavor.',
    'Triple Apple': 'Three apple varieties combined.',
    'Grape Ice': 'Purple grape with ice cooling.',
  },

  // Viho Turbo
  viho_turbo: {
    'Blue Power': 'Powerful blue fruit blend with energy.',
    'Banana Icy': 'Creamy banana with ice crystals.',
    'Passion Fruit Icy': 'Exotic passion fruit with cooling.',
    'Watermelon Cactus Jack': 'Watermelon with prickly pear cactus.',
    'Watermelon Bubble Gum': 'Watermelon bubblegum nostalgia.',
    'White Gummy': 'White gummy bear candy flavor.',
    'Coconut Pineapple': 'Tropical coconut and pineapple blend.',
    'Strawberry Raspberry': 'Berry duo with perfect balance.',
    'Watermelon Icy': 'Crisp watermelon with Turbo cooling.',
    'Raspberry Watermelon': 'Tart raspberry meets sweet watermelon.',
    'Blue Razz Icy': 'Blue raspberry with maximum ice.',
    'Cherry Berry': 'Cherry-forward berry blend.',
    'Cherry Lemon': 'Cherry lemonade summertime flavor.',
    'Strawberry Banana': 'Classic smoothie combination.',
    'Frozen Tundra': 'Ultimate ice experience.',
    'Sour Apple Icy': 'Sour apple with frozen finish.',
    'Strawberry Ice': 'Pure strawberry with cooling.',
    'Strawberry Kiwi': 'Perfect strawberry-kiwi balance.',
    'Peach Icy': 'Georgia peach with ice crystals.',
    'Pink Lemonade': 'Sweet pink lemonade recreation.',
    'Sour Apple Watermelon': 'Unique sour fruit combination.',
    'Peppermint Cream': 'Creamy peppermint dessert.',
    'Mango Icy': 'Tropical mango with cooling.',
    'Grape Ice': 'Grape with Turbo ice technology.',
    'Sour Raspberry Bubblegum': 'Sour raspberry gum flavor.',
    'Glazed Donut': 'Sweet glazed donut dessert.',
    'Glacier O Real': 'Cool spearmint and wintergreen with a touch of eucalyptus creating an icy fresh breath sensation.',
    'Tropical Melon': 'Mixed tropical melons.',
    'Rainbow Pop': 'Rainbow popsicle flavor.',
    'Popping Candy': 'Fizzy popping candy experience.',
    'La Mint': 'Los Angeles-inspired mint blend.',
    'Peach Lemon': 'Peach lemonade combination.',
  },

  // Hyde Rechargeable 3300
  hyde_3300: {
    'Minty O': 'Hyde\'s original mint circle candy with cooling crystals.',
    'Blue Razz': 'Classic Hyde blue raspberry formula.',
    'Mango Peaches and Cream': 'Creamy mango and peach dessert blend.',
    'Pineapple Ice': 'Tropical pineapple with Hyde\'s ice formula.',
    'Cherry Peach Lemonade': 'Three-way fruit lemonade blend.',
    'Summer Luv': 'Hyde\'s summer fruit love letter.',
    'Sour Apple Ice': 'Tart green apple with cooling.',
    'Power': 'Energy drink flavor with citrus, berry, and taurine-like notes for a boost sensation.',
    'Raspberry Watermelon': 'Classic Hyde berry-melon combination.',
    'Aloe Grape': 'Unique aloe vera with grape.',
    'Peachy': 'Pure peach perfection by Hyde.',
    'Strawberry Orange Ice': 'Citrus-berry blend with cooling.',
    'OJ': 'Fresh squeezed orange juice flavor.',
    'Pink Lemonade': 'Hyde\'s pink lemonade stand special.',
    'Lush Ice': 'Watermelon with intense cooling.',
    'Peach Mango Watermelon': 'Triple fruit tropical blend.',
    'Strawberry Kiwi': 'Classic combination Hyde style.',
    'Banana Ice': 'Creamy banana with ice finish.',
    'Pina Colada': 'Tropical cocktail recreation.',
    'Strawberry Banana': 'Smoothie-inspired blend.',
    'Strawberry Ice Cream': 'Creamy strawberry dessert.',
    'Tropical': 'Hyde\'s tropical fruit medley.',
  },

  // RYL Classic by RAZZ
  ryl: {
    'Blue raz ice': 'Sweet blue raspberry hard candy with cooling menthol creating a frozen berry treat.',
    'Watermelon ice': 'Classic watermelon with RYL\'s cooling formula.',
    'Triple berry': 'Strawberry, blueberry, and raspberry creating a sweet mixed berry medley.',
    'Miami mint': 'Spearmint and wintergreen with coconut cream undertones for a smooth mint experience.',
    'Night crawler': 'RYL\'s blend of blackberry, blueberry, and dark cherry with grape undertones for a sweet night vape.',
    'Icy mint': 'Pure icy mint with maximum cooling effect.',
    'White yummy ice': 'White gummy candy with ice crystals.',
    'Raspberry watermelon': 'Tart raspberry meets sweet watermelon.',
    'Sour strawberry': 'Strawberry with intense sour coating.',
    'Dragonfruit lemonade': 'Exotic dragon fruit mixed with lemonade.',
    'Rainbow': 'Rainbow candy with multiple fruit flavors.',
    'Sour apple': 'Green apple with sour candy coating.',
    'Orange mango': 'Citrus orange meets tropical mango.',
    'Peach passion fruit': 'Southern peach with exotic passion fruit.',
    'Blue razz bliss': 'Blissful blue raspberry experience.',
    'Wild berry dew': 'Wild berries with mountain dew freshness.',
    'Banana ice': 'Creamy banana with cooling finish.',
    'Sour apple ice': 'Sour apple with double ice effect.',
  },

  // Razz Mega additional flavors
  razz_mega_extra: {
    'New York mint': 'Big Apple-inspired mint blend with urban coolness.',
    'White grape gush': 'Gushing white grape with candy sweetness.',
    'Polar ice': 'Arctic-level menthol for extreme cooling.',
    'Vicky': 'Pink lemonade with strawberry and raspberry notes, creating Razz\'s signature sweet-tart flavor.',
  },

  // Lost Mary MT15000 additional flavors
  lmmt15000_extra: {
    'Pure': 'Flavorless vape with just the natural slight sweetness of the VG/PG blend.',
    'Watermelon ice': 'Classic watermelon with MT15000 cooling.',
    'Raspberry banana': 'Tart raspberry with creamy banana.',
    'Winter mint': 'Seasonal mint blend with winter freshness.',
    'Strawberry banana': 'Classic smoothie combination.',
    'Rocket popsicle': 'Red, white, and blue popsicle recreation.',
    'Dr. Cherry': 'Cherry cola soda with hints of vanilla, almond, and caramel like Dr Pepper.',
  },

  // Viho Supercharge Pro additional flavors
  viho_sp_extra: {
    'clear': 'No flavor additives - clean, pure vapor with minimal sweetness.',
    'watermelon rollz': 'Watermelon fruit roll candy recreation.',
    'strawberry lemonade': 'Sweet strawberry mixed with tart lemonade.',
    'Sour skittles': 'Sour version of rainbow candy.',
    'Lemon drop': 'Classic lemon drop hard candy.',
  },

  // Viho Supercharge additional flavors
  viho_s_extra: {
    'crispy apple berry': 'Crisp apple with mixed berry blend.',
  },

  // Viho Turbo additional flavors
  viho_turbo_extra: {
    'Dragon fruit watermelon': 'Exotic dragon fruit meets summer watermelon.',
    'Watermelon berries': 'Watermelon enhanced with mixed berries.',
    'Grape bubble gum': 'Purple grape bubblegum nostalgia.',
  },

  // Hyde 3300 additional flavors
  hyde_3300_extra: {
    'Berry ice cream': 'Mixed berry ice cream dessert.',
    'Really Blueberry': 'Intense blueberry flavor that\'s really blue.',
    'Watermelon ice cream': 'Watermelon ice cream bar recreation.',
    'Pink drink': 'Pink beverage-inspired blend.',
    'Energize': 'Red Bull-style energy drink with citrus, berry, and vitamin-like tang.',
  },

  // Geek Bar Pulse additional flavors
  pulse_extra: {
    'B burst': 'Blue raspberry, blueberry, and blackberry triple berry burst with a sweet candy finish.',
    'Sour apple ice': 'Sour green apple with Pulse cooling.',
  },

  // Adjust additional flavors
  adjust_extra: {
    'Black razz baja': 'Black raspberry with Baja blast inspiration.',
  },

  // Lost Mary MO5000 additional flavors
  mo5000_extra: {
    'Black Mint': 'Dark mint variety with unique cooling.',
    'Blue Razz Ice': 'MO5000\'s blue raspberry ice blend.',
    'Citrus sunrise': 'Morning citrus blend with energy.',
    'Alphonso mango ice': 'Premium Alphonso mango with cooling.',
    'Ginger beer': 'Spicy ginger beer soda recreation.',
  },

  // VIHO Supercharge Nicotine Free
  viho_supercharge_nicfree: {
    // This product might not have flavors yet or uses same as regular Supercharge
  },

  // Additional products
  viho_trx_50k: {
    'Lemon Refresher': 'Zesty lemon citrus with a refreshing twist, VIHO TRX\'s take on summer refreshment.',
    'Mango Tango': 'Tropical mango dancing with exotic fruit notes for a tangy sweet experience.',
    'Clear': 'Unflavored option with clean vapor and natural base sweetness only.',
    'Watermelon Ice': 'Crisp watermelon with TRX\'s advanced cooling system for ultimate refreshment.',
    'Sour Apple Ice': 'Tart green apple with sour coating and icy finish, maximized for 50K puffs.',
    'Sour Skittles': 'Rainbow of sour fruit flavors inspired by the classic candy.',
    'Banana taffy ice': 'Creamy banana taffy candy with TRX cooling technology.',
    'Blackberry blizzard': 'Dark blackberry in a blizzard of ice for intense berry cooling.',
    'Cool mint': 'Pure, refreshing mint optimized for the TRX 50K system.',
    'Sour straws': 'Sour rainbow straw candy with tangy fruit coating.',
    'Strawberry banana': 'Classic smoothie blend perfected for extended vaping.',
    'Miami mint': 'Cool spearmint, peppermint, and wintergreen with tropical coconut notes.',
    'Blueberry watermelon': 'Sweet blueberries meet juicy watermelon for perfect balance.',
    'Blue razz ice': 'Bold blue raspberry candy with menthol and crushed ice for a frozen berry slush.',
    'Tobacco': 'Classic tobacco with earthy, woody notes and hints of caramel sweetness.',
  },
  
  fogger_switch_pro_kit: {
    'Pineapple coconut': 'Tropical pineapple with creamy coconut for a piña colada vibe.',
    'Strawberry ice': 'Fresh strawberries with Fogger\'s cooling technology.',
    'Omg blowpop': 'Cherry and blue raspberry blow pop candy with a sweet bubblegum center flavor.',
    'frozen blueberry': 'Flash-frozen blueberries with icy sensation.',
    'gummy bear': 'Mixed fruit gummy bear candy flavor.',
    'strawberry kiwi': 'Classic strawberry-kiwi combination.',
    'grape slush': 'Purple grape slush drink with icy texture.',
    'kiwi dragon berry': 'Kiwi, dragon fruit, and mixed berries.',
    'watermelon ice': 'Crisp watermelon with cooling finish.',
    'strawberry watermelon': 'Summer fruit duo perfectly balanced.',
    'frozen lemon': 'Frozen lemonade with tart citrus.',
    'Strawberry cupcake': 'Sweet strawberry dessert with cake notes.',
    'Blueberry watermelon': 'Blueberry and watermelon fusion.',
    'Sour blue dust': 'Blue raspberry with sour powder coating.',
    'frozen watermelon': 'Sub-zero watermelon freeze.',
    'juicy peach ice': 'Ripe peach with cooling effect.',
    'orange slush': 'Orange slush drink with citrus zest.',
    'blue razz ice': 'Blue raspberry with ice crystals.',
    'strawberry banana': 'Smoothie-inspired blend.',
    'cola slush': 'Frozen cola with authentic soda flavor.',
    'sour apple ice': 'Tart apple with sour and ice.',
    'frozen banana': 'Creamy frozen banana treat.',
  },
  
  fogger_switch_pod: {
    'blue razz ice': 'Blue raspberry ice for Fogger pods.',
    'juicy peach ice': 'Peachy sweetness with cooling.',
    'watermelon ice': 'Watermelon with menthol chill.',
    'miami mint': 'Fresh spearmint with peppermint and a touch of coconut sweetness.',
    'blueberry watermelon': 'Berry and melon combination.',
    'gummy bear': 'Fruity gummy candy flavor.',
    'sour gush': 'Sour fruit gusher candy.',
    'strawberry watermelon': 'Classic summer fruit blend.',
    'watermelon bubble gum': 'Watermelon bubblegum nostalgia.',
    'strawberry kiwi': 'Sweet and tangy fruit mix.',
    'pineapple coconut': 'Tropical island blend.',
    'sour apple ice': 'Sour apple with freeze.',
    'cool mint': 'Refreshing mint for pods.',
  },
  
  hyde_iq: {
    'jolly sour apple ice': 'Green apple hard candy with intense sourness and menthol cooling, like frozen Jolly Rancher.',
    'blue drink': 'Blue sports drink flavor with citrus and berry notes, similar to blue Gatorade.',
    'Jungle juice': 'Tropical fruit punch party mix.',
    'watermelon chew': 'Chewy watermelon candy.',
    'lemon drop': 'Classic lemon drop candy.',
    'strawberry limeaid ice': 'Strawberry limeade with cooling.',
    'kiwi apple pomberry ice': 'Triple fruit blend with ice.',
    'killa confetti': 'Birthday cake confetti explosion.',
    'apple peach watermelon': 'Three-fruit summer blend.',
    'peach blueberry': 'Peach and blueberry harmony.',
    'mystery mix': 'Tropical fruit medley with pineapple, mango, passion fruit, and citrus creating Hyde\'s signature mix.',
    'watermelon fix': 'Intense watermelon satisfaction.',
    'pink burst': 'Pink candy burst of flavor.',
    'dragonberry cotton clouds': 'Dragon fruit and berry with cotton candy.',
    'dew': 'Citrus soda with lemon-lime, orange, and grapefruit creating a Mountain Dew taste.',
    'cranberry lime fix': 'Tart cranberry with lime zest.',
    'pink drink': 'Pink beverage-inspired blend.',
    'blue raz peach bears ice': 'Blue razz and peach gummy bears with ice.',
  },
  
  tyson_heavyweight: {
    'Apple peach': 'Crisp apple meets soft peach, a heavyweight combination.',
    'Mango Lychee': 'Tropical mango with exotic lychee for a knockout flavor.',
    'Apple melonberry': 'Apple, melon, and berry triple threat.',
    'lemon berry': 'Citrus lemon with mixed berry sweetness.',
    'peach watermelon': 'Southern peach meets summer watermelon.',
    'pineapple melon': 'Tropical pineapple with honeydew melon.',
    'pineapple mango': 'Double tropical punch of flavor.',
    'frozen mango': 'Icy mango with championship cooling.',
    'lush lime': 'Intense lime with lush sweetness.',
    'Mintberry': 'Fresh mint with berry combination.',
  },
  
  mood_bar_air: {
    'Kiwi melon pineapple ice': 'Triple tropical fruit with cooling sensation.',
    'fuji apple tangerine ice': 'Crisp Fuji apple with tangerine citrus and ice.',
    'strawberry mango cream': 'Creamy strawberry and mango dessert.',
    'passionfruit guava citrus': 'Exotic passion fruit and guava with citrus notes.',
    'strawberry grape ice': 'Berry and grape duo with cooling.',
    'blood orange': 'Intense blood orange citrus.',
    'clear': 'No flavor - just clean vapor with the natural sweetness of the base liquid.',
    'strawberry peach': 'Sweet strawberry and peach blend.',
    'white gummy': 'White gummy bear candy flavor.',
  },
  
  kumi_six_10000: {
    'watermelon ice': 'KUMI\'s watermelon with NONIC6 and cooling.',
    'mystery ice': 'Mixed tropical fruits including lychee, guava, and passion fruit with a cooling menthol finish.',
    'strawberry fanta': 'Fizzy strawberry soda with carbonated sensation and candy strawberry sweetness.',
    'banana ice': 'Creamy banana with cooling effect.',
    'blue razz': 'Classic blue raspberry.',
    'cool mint': 'Refreshing mint blend.',
    'peach ice': 'Sweet peach with ice crystals.',
    'sour wave': 'Wave of sour fruit flavors.',
  },
  
  viho_supercharge_nicfree: {
    // Add nicotine-free specific descriptions if needed
  },
  
  pulse_bar_pro: {
    // Flavors coming soon - no descriptions needed yet
  },
};
